// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebStore.Data.Contexts;

#nullable disable

namespace WebStore.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241127104517_AddSeedCategoryToDB")]
    partial class AddSeedCategoryToDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebStore.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "phone"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Iphone"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "TVs"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 5,
                            Name = "Microwive"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
